package com.malcolmcrum.vehiclesurvey;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public static void main(String[] args) {
		if (args.length == 0) {
			abort("An argument is missing. Usage: <jar> <vehicledata.txt>");
		}
		Path file = validateFile(args[0]);
		SensorData sensors = null;
		try {
			sensors = SensorData.parse(file);
		} catch (IOException e) {
			abort("Failed trying to read file " + file + ": " + e.getMessage());
		}
		Survey survey = new Survey(sensors);
	}

	private static Path validateFile(String path) {
		Path file = Paths.get(path);
		if (Files.notExists(file)) {
			abort("The provided file does not exist: " + path);
		}
		return file;
	}

	private static void abort(String reason) {
		System.out.println(reason);
		System.exit(1);
	}
}
